### ISSUE TITLE
Implement Semantic Versioning

### ISSUE THREAD

**Issue by rgnote** [notaryproject/notation-go#102]
Notary V2 uses [SemVer](https://semver.org/) for plugin versioning. See [spec here](https://github.com/notaryproject/notaryproject/blob/c4400ebb2da98bce89e66cc8fadeddae564e2b61/signature-specification.md?plain=1#L153-L156)
At the time of writing this issue, Golang has no standard library support for parsing or comparing SemVer strings. This issue is to track implementing SemVer in Notation if no alternative is available. This issue is blocking using `verification plugin minimum version` critical attribute in signature verification workflow.

code: https://github.com/notaryproject/notation-go/blob/7e391f7562e4249272b8f3b271cc33ba4380775f/verifier/verifier.go#L127-L128

**Comment by shizhMSFT** [comment]
@rgnote Golang has standard library support for parsing and comparing SemVer strings. Those libraries are live in the `go mod` repo (see [github.com/golang/mod](https://github.com/golang/mod)) where the semver package is available [here](https://pkg.go.dev/golang.org/x/mod/semver).

**Comment by rgnote** [comment]
@shizhMSFT Couple of issues with `x/mod`

1. It requires versions to be prefixed with `v`
2. Allows partial strings such as `1`, `1.0`, etc.

We may need to write a wrapper around it to make it work with Notation.

**Comment by priteshbandi** [comment]
PR https://github.com/notaryproject/notation-go/pull/237
