### ISSUE TITLE
Release a new version of Notation-go libraries 

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/notation-go#109]
It's time to release a new version for Notation-go repo

- [x] Decide on main commit for this release
- [x] Decide on a tag name for this release
- [x] Cut branch named with the tag name based on agreed upon main commit
- [x] Cut a tag 

@gokarnm @iamsamirzon @dtzar @SteveLasker @FeynmanZhou @shizhMSFT @yizha1 @vaninrao10

**Comment by yizha1** [comment]
@vaninrao10 @iamsamirzon there are dependencies among three repos under notaryproject. notation CLI depends on notation-go, and notation-go depends on notation-core-go. So, the release process looks like this:

- Release library notation-core-go
- Update go.mod in notation-go for notation-core-go dependency
- Release library notation-go
- Update go.mod in notation CLI for notation-go dependency
- Release notation CLI

So, it's better to let one team release all three repos, my suggestion would be this time I take over the release for all three repos.

**Comment by yizha1** [comment]
This PR needs to be merged for updating the dependencies:
- https://github.com/notaryproject/notation-go/pull/112

**Comment by yizha1** [comment]
use version v0.10.0-alpha.3

**Comment by yizha1** [comment]
notation-go released, https://github.com/notaryproject/notation-go/tree/v0.10.0-alpha.3, this issue can be closed soon.
