### ISSUE TITLE
Perform X509 revocation check in signature verification

### ISSUE THREAD

**Issue by rgnote** [notaryproject/notation-go#110]
Signature verification needs to perform x509 revocation check (CRL/OCSP) and fail if a certificate in the chain is revoked.

See https://github.com/notaryproject/notaryproject/blob/main/trust-store-trust-policy-specification.md#certificate-revocation-evaluation

**Comment by yizha1** [comment]
Update the milestone to rc-3 based on the [discussion](https://hackmd.io/WVFhrhvYSFutJpnY6JTDuQ?view#RC-3-Release-Items---March-30th-2023-Can-be-called-GA-----Gives-5-weeks-after-rc-2-release).

**Comment by vaninrao10** [comment]
We both OCSP and CRL for revocation check, Aligned in the community meeting on 11/11 and can be closed.
