### ISSUE TITLE
Resolve bug in oras-go to enable interop with OCI compliant registries like ECR

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/notation-go#116]
As a user of Notation I want to use it to push and pull signatures from ECR.

- [ ] https://github.com/oras-project/oras-go/issues/225 , blocks the above.

Notation open source maintainers will work with ORAS-go maintainers to resolve the above issue, and release a new version of oras-go client, that Notation can use. Likely v2.0.0-rc.3 Milestone ( [refer v2.0.0-rc.3](https://github.com/oras-project/oras-go/milestone/8) )

**Comment by iamsamirzon** [comment]
@vaninrao10  - Assigning this to you to help track progress

**Comment by vaninrao10** [comment]
This was checked in and ( [refer v2.0.0-rc.3] is available.
