### ISSUE TITLE
Add more validations for timestamp response

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation-go#13]
We do need to add more validation for timestamp response to avoid MitM, replay, etc. attacks and also to be a compliant client. The validations are more from timestamp security and correctness perspective. If the timestamp signature is bad then it is of no use for users.

Haven't gone through complete rfc3161 but here are some notable mentions:
* MitM and replay attack: https://datatracker.ietf.org/doc/html/rfc3161#section-4 point 4 and 5
* Policy: https://datatracker.ietf.org/doc/html/rfc3161#section-2.2
* nonce https://datatracker.ietf.org/doc/html/rfc3161#section-2.4.1
* PKIStatus,PKIFailureInfo https://datatracker.ietf.org/doc/html/rfc3161#section-2.4.2

_Originally posted by @priteshbandi in https://github.com/notaryproject/notation-go-lib/pull/11#discussion_r719978761_

**Comment by vaninrao10** [comment]
As per the meeting note on sep, 19th "https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?view#Sep-19-2022 " this will be moved to RC-2 similar to https://github.com/notaryproject/roadmap/issues/59

**Comment by priteshbandi** [comment]
Removing RC2 milestone as its been tracked in parent issue https://github.com/notaryproject/roadmap/issues/59
