### ISSUE TITLE
Notation-go supporting OCI reference type

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation-go#136]
`Notation-go` depends on `ORAS-go` to support OCI reference type. The `ORAS-go` work item is tracked here at https://github.com/oras-project/oras-go/issues/271. Besides the update in `ORAS-go`, this issue tracks any other tasks of `notation-go` to support OCI reference type.

**Comment by FeynmanZhou** [comment]
https://github.com/oras-project/oras-go/issues/271 is completed in ORAS-go v2.0.0-rc.4 and it was released. I think we should update the milestone from `Discuss` to `RC-1` and bump the ORAS-go dependency in RC-1 this month.

**Comment by patrickzheng200** [comment]
Closing this issue since the notation-go refactoring work resolved it.
