### ISSUE TITLE
directory structure needs to isolate `read` and `write` path

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#144]
As current design, when system level directory has the config file while user level directory doesn't have the config file, it uses the system level config file for read and write. 

It is necessary to allow the user to know that whether the write path is user level or system level, so we need to:
1. isolate `read` /`write` path
2. provide the ability to select `user`/`system` level directory to write.
Linked to [System vs User file/directory precedence#203](https://github.com/notaryproject/notation/issues/203)

**Comment by yizha1** [comment]
@shizhMSFT  @JeyJeyGao  Can we close this issue since there is no requirement to support "system" level directory.
