### ISSUE TITLE
Adding Notary v2 payload validation

### ISSUE THREAD

**Issue by chloeyin** [notaryproject/notation-go#154]
Currently, `notation-go` and `notation-core-go` don't validate the content type of the payload as described in the [spec](https://github.com/notaryproject/notaryproject/blob/main/signature-specification.md#payload). As discussed in the https://github.com/notaryproject/notation-go/pull/131#discussion_r979508855, create an issue here to discuss if we need to do the validation.

**Comment by Two-Hearts** [comment]
Closing as this issue has been completed by PR: https://github.com/notaryproject/notation-go/pull/200.
