### ISSUE TITLE
Release a new version of notation-go library

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation-go#176]
- [x] Decide on main commit for this release
- [x] Update dependencies in go.mod
- [x] Decide on a tag name for this release
- [x] Tag name: v0.12.0-beta.1
- [x] Cut a tag

/cc @dtzar @FeynmanZhou @iamsamirzon @vaninrao10 @shizhMSFT

**Comment by yizha1** [comment]
- [ ] Bump up notation-core-go version in go.mod to `v0.2.0-beta.1`

**Comment by priteshbandi** [comment]
https://github.com/notaryproject/notation-go/releases/tag/v0.12.0-beta.1
