### ISSUE TITLE
plugin output size limitation

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#187]
The plugin is an external binary which may generate very large command line output and will be loaded to memory by notation-go library. 
Do we need a plugin output size limitation?

**Comment by vaninrao10** [comment]
We aligned in the community meeting on 11/11 and finalized that we need pursue with the limitation option. Further discussion how to solution is pending.
Customer should trust the plugin, all of the output should satisfy the requirement and not generate large content. Will it crash if the memory is overloaded. Document security best practices and customer need to define what is the size limit.

**Comment by JeyJeyGao** [comment]
Tested on Linux. A very large plugin output triggers the OS to kill the process. We need to fix it.
