### ISSUE TITLE
doc: provide API documentation and API architecture diagram for notation-go

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation-go#189]
Currently, notation-go is [refactoring its interface and architecture](https://hackmd.io/nAV5ipF1TKyxFdrO7_75Mg) and evolving into a generic Golang library.

Developing a generic and extensible library is also critical for other projects to consume Notation API and extend the Notation ecosystem. Take this [falcoctl sign and verify commands](https://github.com/falcosecurity/falcoctl/issues/174) as an example, if Notation-go can provide corresponding API docs for library users, it will be easy for other projects to use the signing and verifying interfaces. Creating an API architecture diagram will help users understand the logic in Notation-go. 

I hope this work can be planned in the RC.2 release. 

- [x] Update the API doc & examples and publish it on https://pkg.go.dev/github.com/notaryproject/notation-go
- [x] Creating an API architecture diagram in Notation-go repo (README)

**Comment by FeynmanZhou** [comment]
cc @JeyJeyGao @patrickzheng200 @shizhMSFT @priteshbandi @vaninrao10 @yizha1

**Comment by vaninrao10** [comment]
I 100% agree with this. LGTM

**Comment by FeynmanZhou** [comment]
The API doc & example have been updated at https://pkg.go.dev/github.com/notaryproject/notation-go#pkg-examples. So I close this issue as completed.
