### ISSUE TITLE
Release notation-go-lib-v0.7.0-alpha.1

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/notation-go#19]
Proposing we release notation-go-lib-v0.7.0-alpha.1 as we have completed the milestone. Release process is defined here.

High level deliverables as as follows:

- [x]  Decide on main commit for release
- [ ] Cut branch named v0.7.0-alpha.1 based on agreed upon main commit
- [x]  Cut a tag named v0.7.0-alpha.1
- [ ]  Update README.md

/cc @SteveLasker @NiazFK @justincormack @sajayantony

Can the maintainers please respond with a +1 comment once you are in favor of cutting this release.

**Comment by SteveLasker** [comment]
LGTM [6f3abd7](https://github.com/notaryproject/notation-go-lib/commit/6f3abd71b7a029bb28ac1f80cb4638e73ab3a4fe)

**Comment by dtzar** [comment]
@iamsamirzon @SteveLasker - I believe this is complete now...

All this said - It would be great to discuss release strategy and document something for ongoing work.

**Comment by iamsamirzon** [comment]
I concur with your David.

**Comment by shizhMSFT** [comment]
Closed as `v0.7.0-alpha.1` has been released.
