### ISSUE TITLE
Replace strings.Index() with strings.Cut()

### ISSUE THREAD

**Issue by patrickzheng200** [notaryproject/notation-go#204]
Scan all code to replace 
```
i := strings.Index(s, ":")`
a := s[:i]
b := s[i+1:]
```
with `strings.Cut()`

**Comment by shizhMSFT** [comment]
Original post at https://github.com/notaryproject/notation-go/pull/186/files#r1021155308

**Comment by patrickzheng200** [comment]
I will take this one.
