### ISSUE TITLE
Refine constructors of package `verifier`

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-go#205]
#186 has refactored the package `verifier` according to [this design](https://hackmd.io/nAV5ipF1TKyxFdrO7_75Mg?view) where the constructors of `notation.Verifier` are
```go
func New() (notation.Verifier, error)
func NewVerifier(trustPolicy *trustpolicy.Document, pluginManager plugin.Manager) (notation.Verifier, error)
```

However, the constructor APIs do not match the original design. The constructors should be updated to
```go
func New(trustPolicy *trustpolicy.Document, trustStore truststore.X509TrustStore, pluginManager plugin.Manager) (notation.Verifier, error)
func NewFromConfig() (notation.Verifier, error)
```
to match the original design where `New()` --> `NewFromConfig()`, `NewVerifier()` --> `New()`.

Note: The API naming is consistent with #200.

**Comment by patrickzheng200** [comment]
Got it. Will make the change today.

**Comment by shizhMSFT** [comment]
Here's the diagram to help understanding.
```mermaid
classDiagram
direction LR

Verifier ..> TrustPolicy: Dependency
Verifier ..> TrustStore: Dependency
TrustPolicy --> TrustStore

Verifier ..> PluginManager: Dependency
```

**Comment by shizhMSFT** [comment]
Please also note that the `plugin.Manager` can be `nil` but `*trustpolicy.Document` and `truststore.X509TrustStore` MUST NOT be nil.
