### ISSUE TITLE
Checking the media type after fetching the blob is slow

### ISSUE THREAD

**Issue by patrickzheng200** [notaryproject/notation-go#215]
The performance of this check is slow since it checks the media type after fetching the blob. 
`if len(remoteOpts.SignatureMediaTypes) != 0 && !slices.Contains(remoteOpts.SignatureMediaTypes, sigDesc.MediaType)`

_Originally posted by @shizhMSFT in https://github.com/notaryproject/notation-go/pull/208#discussion_r1030094971_

**Comment by patrickzheng200** [comment]
Closing this issue since we decided to remove this logic in RC-1. If we decide to bring it back in RC-2 we should re-open this issue.

**Comment by Two-Hearts** [comment]
Closing as completed by PR: https://github.com/notaryproject/notation-go/pull/208
