### ISSUE TITLE
Plugin error handling

### ISSUE THREAD

**Issue by zosocanuck** [notaryproject/notation-go#220]
Hi,

I'm testing a plugin prototype (based on [notation-azure-kv](https://github.com/Azure/notation-azure-kv)) that will implement signature generator however when it comes to error handling I seem to be only obtaining the following generic error:

`Error: describe-key command failed: xyz-plugin: ERROR: failed to decode json response: plugin not compliant`

In cmd/xyz-plugin main.go I have:

```
if err := app.Run(os.Args); err != nil {
		var reer plugin.RequestError
		if !errors.As(err, &reer) {
			err = plugin.RequestError{
				Code: plugin.ErrorCodeGeneric,
				Err:  err,
			}
		}
		data, _ := json.Marshal(err)
		os.Stderr.Write(data)
		os.Exit(1)
	}
```
Within the actual runDescribeKey I'm returning a plugin.RequestError per the spec:

```
if err != nil {
			return nil, plugin.RequestError{
				Code: plugin.ErrorCodeValidation,
				Err:  errors.New("custom error message goes here: " + err.Error()),
			}
		}
```
Seems like the plugin handler in notation-go is not correctly handling the returned error?

**Comment by sajayantony** [comment]
+ @shizhMSFT @priteshbandi  might be able to comment on this.

**Comment by JeyJeyGao** [comment]
Hi Ivan @zosocanuck , notation-go package have been refactored. Looks like you were using `plugin.RequestError` which is the old version. After refactor, it should be `proto.RequestError`, so could your have try the notation-go RC.1 again? Please let us know, if you still have issues.

Please try:
```
go get github.com/notaryproject/notation-go@v1.0.0-rc.1
go mod tidy
```
then replace `plugin.RequestError` with `proto.RequestError` and try again.
You should also use [Notation CLI RC.1](https://github.com/notaryproject/notation/releases/tag/v1.0.0-rc.1) to test your plugin.

**Comment by zosocanuck** [comment]
@JeyJeyGao Yes I'm using the latest RC.1 and turns out I was unexpectedly sending log information via os.Stdout, which was causing the issue, and hence would explain the error about the plugin not being compliant.
