### ISSUE TITLE
Notation plug-in design / notation-go-lib integration

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation-go#23]
Issue #22 surfaced an interesting question.
When using Notary v2 from a cli, we direct users to the notation repo and output
When using Notary v2 as a library, for use in other clis, how do we enable the notation plug-ins for specific key vault providers?

The current design enables users to install the notation cli and their desired plug-ins.
If someone uses the notation-go-lib to incorporate an SBoM signing solution, or some other integration, should they have to implement all the plug-in redirection?

Can we create an easy experience for developers to reference the notation-go-lib, and still get normal plug-in capabilities?

**Comment by yizha1** [comment]
closed by #37
