### ISSUE TITLE
the version value of useragent in the signature should be driven by notation release value

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation-go#233]
https://github.com/notaryproject/notation-go/blob/0355e8eb494c3e8f9ecb899f12c06ab333739321/signer/signer.go#L24

The semver, currently `1.0.0` should be set based on notation release which means the value needs to be taken as input from caller of sign method.

**Comment by priteshbandi** [comment]
Adding it as rc2 so that we can triage.

**Comment by priteshbandi** [comment]
This is partially complete;
1. For SignatureGenerator the fix was done as part of https://github.com/notaryproject/notation-go/pull/178
2. **For EnvelopeGenerator fix is pending**

**Comment by vaninrao10** [comment]
This fix by most recent release in notation-go. Everytime new notation-go release, the useragent version is also updated. So, closing this issue.
Reference - https://github.com/notaryproject/notation-go/blob/main/RELEASE_CHECKLIST.md
Aligned in the community meeting on 11/11 to close this issue.
