### ISSUE TITLE
`ExtendedSignedAttributes` cannot be set by notation-go

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#240]
`ExtendedSignedAttributes` is an arguments of notation-core-go `SignRequest`. It passes the extended attributes to be signed. However, we cannot set the argument by notation-go. The extended attributes filed is used by verification. Verify by plugin will be trigger if the signature extended attributes contain `io.cncf.notary.verificationPlugin` fields, so it is necessary to support setting `ExtendedSignedAttributes` in notation-go to help library user and plugin developer.

**Comment by Promaethius** [comment]
https://github.com/notaryproject/notaryproject/blob/main/specs/signature-specification.md#guidelines-for-notary-v2-implementors
