### ISSUE TITLE
trusted identity parsing error was not returned

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#251]
As shown in [the code](https://github.com/notaryproject/notation-go/blob/c90d5213aefafbe60a361398447217fad018a1aa/internal/pkix/pkix.go#L16), the error was handled but didn't return the real error which can help the user locate the issue.

```go
	dn, err := ldapv3.ParseDN(name)
	if err != nil {
		return nil, fmt.Errorf("distinguished name (DN) %q is not valid, it must contain 'C', 'ST', and 'O' RDN attributes at a minimum, and follow RFC 4514 standard", name)
	}
```

**Comment by patrickzheng200** [comment]
Nice catch! Will create a PR and add the corresponding logic.
