### ISSUE TITLE
trust store validation error message needs improvement

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#254]
The trust store validation error message needs improvement. Here is the [code](https://github.com/notaryproject/notation-go/blob/c90d5213aefafbe60a361398447217fad018a1aa/verifier/helpers.go#L58).

```go
storeType, name, found := strings.Cut(trustStore, ":")
if !found {
	return nil, fmt.Errorf("trust policy statement %q is missing separator in trust store value %q", policy.Name, trustStore)
}
```
We had better provide a valid trust store format to help user figure out the value. We can add "Format <TrustStoreType>:<TrustStoreName> is required" to the end of the error message.

**Comment by patrickzheng200** [comment]
To align with the spec, we could say `Format {store-type}:{store-name} is required`
