### ISSUE TITLE
[revocation] Integrate OCSP and CRL support

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation-go#281]
### Pre-requisite: 
1. https://github.com/notaryproject/notation-core-go/issues/124
2. https://github.com/notaryproject/notation-core-go/issues/125

### Tasks
- [ ] Abstract OCSP and CRL check behind a separate module.
- [ ] Call the above module based on [spec](https://github.com/notaryproject/notaryproject/blob/main/specs/trust-store-trust-policy.md#certificate-revocation-evaluation) and trust-policy config.

**Comment by Two-Hearts** [comment]
Closing as completed.
