### ISSUE TITLE
trust store certificates validation issue

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#284]
https://github.com/notaryproject/notation-go/blob/9920fb73937e9b8dbaccc2886ceefefd5a4a3803/verifier/truststore/truststore.go#L107-L127

the `validateCerts` function was called in `X509TrustStore` interface which can be bypassed because the interface can be override by notation-go users. Then, it may cause an leaf cert can be used as a certificate in trust store and cause the verification only checks the leaf certificate.

**Comment by patrickzheng200** [comment]
As we discussed, we will export a function `func ValidateCerts(certs []*x509.Certificate) error`.
Users who implement their own X509TrustStore needs to call ValidateCerts() on their end to make sure certificates in their trust store follows notation's spec.

**Comment by yizha1** [comment]
@patrickzheng200 was this issue solved?

**Comment by patrickzheng200** [comment]
> @patrickzheng200 was this issue solved?

@yizha1 no, the corresponding PR https://github.com/notaryproject/notation-go/pull/285 is pending review.
