### ISSUE TITLE
Vote for release of notation-go v1.0.0-rc.6

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation-go#319]
We need `4` approvals from the current `6` maintainers to vote for tagging [69cf11b](https://github.com/notaryproject/notation-go/commit/69cf11bbbc7641efcee966b22d47495b5a6d274e) as `v1.0.0-rc.6`. Here is the link to [change log](https://github.com/notaryproject/notation-go/compare/v1.0.0-rc.5...69cf11b) .

- [x] Junjie Gao <junjiegao@microsoft.com> (@JeyJeyGao)
- [ ] Milind Gokarn <gokarnm@amazon.com> (@gokarnm)
- [x] Patrick Zheng <patrickzheng@microsoft.com> (@Two-Hearts)
- [x] Pritesh Bandi <priteshbandi@gmail.com> (@priteshbandi)
- [ ] Rakesh Gariganti <garigant@amazon.com> (@rgnote)
- [x] Shiwei Zhang <shizh@microsoft.com> (@shizhMSFT)

----
### change log for v1.0.0-rc6
- https://github.com/notaryproject/notation-go/pull/318
- https://github.com/notaryproject/notation-go/pull/317
- https://github.com/notaryproject/notation-go/pull/316
- https://github.com/notaryproject/notation-go/pull/314
- https://github.com/notaryproject/notation-go/pull/313
- https://github.com/notaryproject/notation-go/pull/312
- https://github.com/notaryproject/notation-go/pull/311
- https://github.com/notaryproject/notation-go/pull/310

**Comment by priteshbandi** [comment]
LGTM

**Comment by Two-Hearts** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by yizha1** [comment]
Thank you, `notation-go` Maintainers. We have enough approvals now.

**Comment by yizha1** [comment]
Released https://github.com/notaryproject/notation-go/releases/tag/v1.0.0-rc.6
