### ISSUE TITLE
Rename notation-go-lib to notation-go

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation-go#33]
Part of the cleanup and refactoring, including the creation of [notation-core-go](https://github.com/notaryproject/notation-core-go)

Please :+1: to confirm

**Comment by SteveLasker** [comment]
👍

**Comment by gokarnm** [comment]
👍

**Comment by iamsamirzon** [comment]
Agree

**Comment by shizhMSFT** [comment]
👍

**Comment by SteveLasker** [comment]
:tada: done
