### ISSUE TITLE
Support go library based plugins

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation-go#336]
### Is your feature request related to a problem?

If a product is consuming notation-go the they should be able to add a library based plugin. This will not only add more security(no plugin cli to manage) but will also need less compute(no new process for sign/verify operation).
 

### What solution do you propose?

To achieve this we will two major changes
1. Add new plugin manager, lets call it [UberManager](https://github.com/priteshbandi/notation-go/blob/lib-plugin/plugin/manager.go#L28-L83)
2. Migrate plugin interface related structs to a new package called [notation-plugin-base] and possibly ease up creation of plugin.
3. Refactor `notation-go` to use the newly created pkg.

**Comment by shizhMSFT** [comment]
> 3. Refactor notation-go to use the newly created pkg.

Is that "Refactor **notation CLI** to use the newly created pkg"?

**Comment by yizha1** [comment]
Closed as discussed with Pritesh.
