### ISSUE TITLE
Adding plugin examples in notation-go

### ISSUE THREAD

**Issue by Two-Hearts** [notaryproject/notation-go#339]
### Is your feature request related to a problem?

I'd like to use plugins with notation-go. A quick start example is helpful for new users.

### What solution do you propose?

Add example to notation-go library.

### What alternatives have you considered?

N/A

**Comment by Two-Hearts** [comment]
Issue created based on discussion in community meeting. /cc: @priteshbandi @shizhMSFT @yizha1 @FeynmanZhou

**Comment by yizha1** [comment]
@priteshbandi Can we close this issue since it is covered by notaryproject/notation-plugin-framework-go?
