### ISSUE TITLE
vote: tag 1.0.1

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-go#360]
## Release

This would mean tagging 765d02b5beedfdc263ed1dba91d1971d444a4742 as `v1.0.1` to release.

## Vote

We need at least `4` approvals from `6` maintainers to release `notation-go v1.0.1`.

- [x] Junjie Gao (@JeyJeyGao)
- [ ] Milind Gokarn (@gokarnm)
- [x] Patrick Zheng (@Two-Hearts)
- [x] Pritesh Bandi (@priteshbandi)
- [ ] Rakesh Gariganti (@rgnote)
- [x] Shiwei Zhang (@shizhMSFT)

## Changes

The code changes compared to `v1.0.0` include:

- #344
- #349
- #350
- #347
- #356
- #351
- #352
- #355
- #359
- #358
- #345

**Full Changelog**: https://github.com/notaryproject/notation-go/compare/v1.0.0...765d02b5beedfdc263ed1dba91d1971d444a4742

## Action Requested

Please respond LGTM or REJECT (with reasoning).

**Comment by Two-Hearts** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by shizhMSFT** [comment]
Closing this issue as [v1.0.1](https://github.com/notaryproject/notation-go/releases/tag/v1.0.1) has been released.
