### ISSUE TITLE
vote: tag 1.1.0

### ISSUE THREAD

**Issue by Two-Hearts** [notaryproject/notation-go#378]
## Release

This would mean tagging b7cd8a01fcdb738939fbced6d803efcbc3e504d8 as `v1.1.0` to release.

## Vote

We need at least `4` approvals from `6` maintainers to release `notation-go v1.1.0`.

- [x] Junjie Gao (@JeyJeyGao)
- [ ] Milind Gokarn (@gokarnm)
- [x] Patrick Zheng (@Two-Hearts)
- [x] Pritesh Bandi (@priteshbandi)
- [ ] Rakesh Gariganti (@rgnote)
- [x] Shiwei Zhang (@shizhMSFT)

## Changes

The code changes compared to `v1.0.1` include:

* build(deps): bump golang.org/x/mod from 0.13.0 to 0.14.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/361
* build(deps): bump golang.org/x/crypto from 0.14.0 to 0.15.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/362
* feat: add uninstall to CLIManager by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/363
* docs: update README to align with the new project brand by @FeynmanZhou in https://github.com/notaryproject/notation-go/pull/343
* build(deps): bump golang.org/x/crypto from 0.15.0 to 0.16.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/366
* feat: add install method to plugin CLIManager by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/364
* build(deps): bump golang.org/x/crypto from 0.16.0 to 0.17.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/367
* feat: plugin install iteration 2 by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/369
* Updated CODEOWNERS and MAINTAINERS files by @toddysm in https://github.com/notaryproject/notation-go/pull/370
* build(deps): bump golang.org/x/crypto from 0.17.0 to 0.18.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/373
* fix: improve plugin error message by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/371
* fix: update PluginExecutableFileError type by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/375
* bump: bump up notation-core-go by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/377

**Full Changelog**: https://github.com/notaryproject/notation-go/compare/v1.0.1...b7cd8a01fcdb738939fbced6d803efcbc3e504d8

## Action Requested

Please respond LGTM or REJECT (with reasoning).

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by Two-Hearts** [comment]
> ~LGTM~
> 
> Should the commit be [b7cd8a0](https://github.com/notaryproject/notation-go/commit/b7cd8a01fcdb738939fbced6d803efcbc3e504d8)?

@shizhMSFT Nice catch. Updated. @JeyJeyGao could you re-vote for the release? Thanks.

**Comment by shizhMSFT** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by Two-Hearts** [comment]
Closing the issue as [v1.1.0](https://github.com/notaryproject/notation-go/releases/tag/v1.1.0) has been released.
