### ISSUE TITLE
Release v0.8.0-alpha

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation-go#38]
Since the library has been renamed to `notation-go` and there are other breaking changes, we need to have a new release of notary at a minimum to make golang package references work well.

/cc @SteveLasker, @justincormack, @sajayantony

Can the maintainers please respond with a +1 comment once you are in favor of cutting this release.

**Comment by SteveLasker** [comment]
👍

**Comment by SteveLasker** [comment]
Adding the release checklist:
- [ ] Decide on main commit for release 
- [ ] Cut branch named `v0.8.0-alpha.1` based on agreed upon main commit
- [ ] Cut a tag named `v0.8.0-alpha.1`
- [ ] Update README.md

**Comment by iamsamirzon** [comment]
+1

**Comment by shizhMSFT** [comment]
Released [v0.8.0-alpha.1](https://github.com/notaryproject/notation-go/releases/tag/v0.8.0-alpha.1)!
