### ISSUE TITLE
Shift Go Support Window to `[1.21, 1.22]`

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-go#386]
[Go 1.22](https://go.dev/blog/go1.22) is released with [release notes](https://go.dev/doc/go1.22)!

It is time to shift the window for go support to `[1.21, 1.22]`.

**Comment by Two-Hearts** [comment]
This issue has been resolved by PR: https://github.com/notaryproject/notation-go/pull/392.

Resolving.
