### ISSUE TITLE
vote: v1.1.1

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#412]
## Release

> [!Note]
> This release doesn't include the #379 as this is a patch release.

The commit 94a0e13a427fcfc9038ae6d12b90bc1cbea70a6b was generated by the following steps:
1. Checked out a new branch `release-1.1` from `main` branch
2. Reverted #379 in PR #411

## Vote

We need at least `4` approvals from `6` maintainers to release `notation-go v1.1.1`.

- [x] Junjie Gao (@JeyJeyGao)
- [ ] Milind Gokarn (@gokarnm)
- [x] Patrick Zheng (@Two-Hearts)
- [ ] Pritesh Bandi (@priteshbandi)
- [ ] Rakesh Gariganti (@rgnote)
- [x] Shiwei Zhang (@shizhMSFT)

## Changes
* fix: update error message by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/380
* bump: bump up oras-go and image-spec by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/381
* chore: start using plugin-framework package by @priteshbandi in https://github.com/notaryproject/notation-go/pull/372
* build(deps): bump golang.org/x/crypto from 0.18.0 to 0.19.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/383
* build(deps): bump github.com/opencontainers/image-spec from 1.1.0-rc6 to 1.1.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/385
* build(deps): bump golang.org/x/mod from 0.14.0 to 0.15.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/384
* chore: updated/added deprecation message by @priteshbandi in https://github.com/notaryproject/notation-go/pull/382
* build(deps): bump golang.org/x/crypto from 0.19.0 to 0.20.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/387
* feat: add support for signing blob by @priteshbandi in https://github.com/notaryproject/notation-go/pull/379
* chore: add GitHub action for stale issues and PRs by @yizha1 in https://github.com/notaryproject/notation-go/pull/365
* build(deps): bump golang.org/x/crypto from 0.20.0 to 0.21.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/389
* build(deps): bump golang.org/x/mod from 0.15.0 to 0.16.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/388
* fix: Add contract version to plugin sign request and plugin verify request by @priteshbandi in https://github.com/notaryproject/notation-go/pull/390
* bump: bump golang and dependency versions by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/392
* build(deps): bump actions/stale from 8 to 9 by @dependabot in https://github.com/notaryproject/notation-go/pull/391
* Moved org maintainers to emeritus by @toddysm in https://github.com/notaryproject/notation-go/pull/393
* build(deps): bump golang.org/x/mod from 0.16.0 to 0.17.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/397
* build(deps): bump github.com/go-ldap/ldap/v3 from 3.4.6 to 3.4.7 by @dependabot in https://github.com/notaryproject/notation-go/pull/395
* build(deps): bump github.com/go-ldap/ldap/v3 from 3.4.7 to 3.4.8 by @dependabot in https://github.com/notaryproject/notation-go/pull/399
* build(deps): bump golang.org/x/crypto from 0.21.0 to 0.22.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/396
* build(deps): bump golang.org/x/crypto from 0.22.0 to 0.23.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/403
* test: improve test coverage to 80% by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/405
* fix: error message for dangling reference index by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/402
* bump: bump up notation-core-go v1.0.3 by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/407
* ci: enable ci for release branch by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/409
* revert: "feat: add support for signing blob (#379)" by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/411

**Full Changelog**: https://github.com/notaryproject/notation-go/compare/v1.1.0...94a0e13a427fcfc9038ae6d12b90bc1cbea70a6b

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by Two-Hearts** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
Closed this vote as [v1.1.1](https://github.com/notaryproject/notation-go/releases/tag/v1.1.1) has been released.
