### ISSUE TITLE
CRL support

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#425]
As suggested in https://github.com/notaryproject/notation-core-go/issues/125, CRL support is required.

Here is the plan to complete CRL support based on priority:
1. **Basic CRL support**  (v1.3.0): This includes `base CRL` downloading and validation, with a fallback rule to automatically choose OCSP and fallback to CRL.
2. **CRL cache support**  (v1.3.0): Since CRL is a static file with relatively long-term validity, and a well-known CA's CRL is usually greater than 600KiB, a cache mechanism can significantly improve performance.

**Comment by priteshbandi** [comment]
LGTM

**Comment by shizhMSFT** [comment]
Cache is important and @JeyJeyGao will share the detailed design later.

**Comment by JeyJeyGao** [comment]
We will use #425 (for notation-go) and https://github.com/notaryproject/notation-core-go/issues/125 (for notation-core-go) to track the CRL support of notation v1.3.0. Other future work items will be tracked in #428

**Comment by Two-Hearts** [comment]
Closing as completed.
