### ISSUE TITLE
vote: v1.2.0-rc.1

### ISSUE THREAD

**Issue by Two-Hearts** [notaryproject/notation-go#439]
## Release

This would mean tagging https://github.com/notaryproject/notation-go/commit/a83c5be7eff0a92a9afc969c9af3b1bbd86e9d0d as `v1.2.0-rc.1` to release.

## Vote

We need at least `4` approvals from `6` maintainers to release `notation-go v1.2.0-rc.1`.

- [x] Junjie Gao (@JeyJeyGao)
- [ ] Milind Gokarn (@gokarnm)
- [x] Patrick Zheng (@Two-Hearts)
- [x] Pritesh Bandi (@priteshbandi)
- [ ] Rakesh Gariganti (@rgnote)
- [x] Shiwei Zhang (@shizhMSFT)

## What's Changed
* fix: improve error message for plugin by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/406
* feat: support distinguished name state(S) by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/432
* refactor!: update revocation based on notation-core-go by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/429
* refactor!: remove blob sign/verify related code by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/437

**Full Changelog**: https://github.com/notaryproject/notation-go/compare/v1.2.0-beta.1...a83c5be7eff0a92a9afc969c9af3b1bbd86e9d0d

## Action Requested

Please respond LGTM or REJECT (with reasoning).

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by Two-Hearts** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by Two-Hearts** [comment]
Closing as released has completed.
