### ISSUE TITLE
vote: Release v1.1.2

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#456]
## Release

This would mean tagging 99da55542dd793cf92c452d24e930d2b5b183ba7 `v1.1.2` to release.

## Vote

We need at least `4` approvals from `6` maintainers to release `notation-go v1.1.2`.

- [x] Pritesh Bandi (@priteshbandi)
- [x] Junjie Gao (@JeyJeyGao)
- [ ] Rakesh Gariganti (@rgnote)
- [ ] Milind Gokarn (@gokarnm)
- [x] Shiwei Zhang (@shizhMSFT)
- [x] Patrick Zheng (@Two-Hearts)

## What's Changed
* fix&bump: maintenance update for branch `release-1.1` by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/448
* fix: dir no longer panics when HOME and XDG_CONFIG_HOME are not set (#449)  by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/450
* bump: release v1.1.2 by @JeyJeyGao in https://github.com/notaryproject/notation-go/pull/453

**Full Changelog**: https://github.com/notaryproject/notation-go/compare/v1.1.1...99da55542dd793cf92c452d24e930d2b5b183ba7

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by Two-Hearts** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
Close the issue as [v1.1.2](https://github.com/notaryproject/notation-go/releases/tag/v1.1.2) has been released.
