### ISSUE TITLE
New release v0.9.0-alpha.1

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation-go#48]
Lots of important changes merged since v0.8.0 and should cut a new release.  
Would like to just take what's on main now plus merge #44 

- [x] Decide on main commit for a release 
- [x]  Cut branch named `v0.9.0-alpha.1` based on agreed upon main commit
- [x] Cut a tag named `v0.9.0-alpha.1`

@SteveLasker @gokarnm @iamsamirzon @FeynmanZhou

**Comment by iamsamirzon** [comment]
Thanks @dtzar   for driving a release of Notation/Notation-go. I am particularly interested in seeing this issue ( https://github.com/notaryproject/notation/issues/119) fixed in this next release. Refer discussion here https://github.com/notaryproject/notation/discussions/170

**Comment by SteveLasker** [comment]
@iamsamirzon, would like to pull in -u, -p for ecr support.

**Comment by dtzar** [comment]
@iamsamirzon - I'd like to still cut this release but now that there has been a number of changes since the request (28 days ago), I think we should stick to committing it with the [version around this same date](https://github.com/notaryproject/notation-go/tree/fe1997f6c65f9015a8b9e9745e041edcb9e3dc9a) to help illustrate the cli and go library were working/tested together at this time (both 0.9.0) which was the original intent.

The issue mentioned workaround is a problem with oras-go and even if we release a new version of this library it won't matter.

**Comment by iamsamirzon** [comment]
Thanks @dtzar . That works.

**Comment by dtzar** [comment]
Once someone approves/merges https://github.com/notaryproject/notation-go/pull/65 then I'll cut this release.

**Comment by FeynmanZhou** [comment]
> Once someone approves/merges #65 then I'll cut this release.

I think this issue does not rely on #65 , @shizhMSFT [explained the reason](https://github.com/notaryproject/notation-go/pull/65#pullrequestreview-1019275304) under that PR. 

@dtzar Could you check if #65 is necessary for this release?

**Comment by dtzar** [comment]
Yes, Shiwei's response makes sense.  I started to investigate alternative approaches to helping automate release notes.  I'm not going to hold up releasing this on the PR.

**Comment by dtzar** [comment]
v0.9.0-alpha.1 is released.
