### ISSUE TITLE
End to End Test Cases

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation-go#52]
**Summary**
Automated Test Cases to be executed before every release for all APIs
**Intended Outcome**
A test suite is created over time and added iteratively over the lifetime of this project development
**Additional context**
The unit testing will be included in RC-1. The community met on 5/26 and made the decision to split this work as unit and end to end testing.

**Comment by yizha1** [comment]
unit test on API level was done by `notation-go` refactoring.
