### ISSUE TITLE
Some unit tests fail on Windows platforms

### ISSUE THREAD

**Issue by Wwwsylvia** [notaryproject/notation-go#57]
Some unit tests in [store_test.go](https://github.com/notaryproject/notation-go/blob/main/verification/store_test.go) fail on Windows platforms, and the error message is like below:
> --- FAIL: TestLoadTrustStoreWithSymlinks (0.01s)
    store_test.go:28: symlinks should return error : "Error while reading certificates from \"testdata\\\\trust-store\\\\trust-store-with-cert-symlinks\\\\GlobalSignRootCA_SYMLINK.crt\". Error : \"x509: malformed certificate\""
--- FAIL: TestLoadTrustStoreWithDirs (0.00s)
    store_test.go:35: sub directories should return error : "\"testdata\\\\trust-store\\\\trust-store-with-directories\\\\sub-dir\" is not a regular file (directories or symlinks are not supported)"
--- FAIL: TestLoadTrustStoreWithInvalidCerts (0.00s)
    store_test.go:42: invalid certs should return error : %!q(<nil>)
--- FAIL: TestLoadTrustStoreWithLeafCerts (0.01s)
    store_test.go:49: leaf cert in a trust store should return error : "certificate with subject \"CN=lol,OU=lol,O=lol,L=lol,ST=Some-State,C=AU,1.2.840.113549.1.9.1=#13036c6f6c\" from file \"testdata\\\\trust-store\\\\trust-store-with-leaf-certs\\\\non-ca.crt\" is not a CA certificate, only CA certificates (BasicConstraint CA=True) are allowed"
FAIL
FAIL    github.com/notaryproject/notation-go/verification       4.042s
FAIL

It's because these test functions check the returned error by comparing its error message with a hard-coded error string, but the returned error message contains a Windows-style path which does not match the hard-coded path (See  [TestLoadTrustStoreWithInvalidCerts](https://github.com/notaryproject/notation-go/blob/main/verification/store_test.go#L39-L44)).

**Comment by rgnote** [comment]
https://github.com/notaryproject/notation-go/pull/58

**Comment by yizha1** [comment]
Closed by #58
