### ISSUE TITLE
Support TSA trust stores in trust policy

### ISSUE THREAD

**Issue by rgnote** [notaryproject/notation-go#74]
See https://github.com/notaryproject/notation-go/pull/72#discussion_r914513445

**Comment by iamsamirzon** [comment]
@rgnote   - Can we close this?

**Comment by vaninrao10** [comment]
Linked to https://github.com/notaryproject/notation-go/issues/74

**Comment by yizha1** [comment]
Closed this issue as TSA trust store is supported.
