### ISSUE TITLE
Reenable timestamping for signing and verification

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation-go#78]
As part of #77(Refactor to use notation-core-go's SignatureEnvelope), we disabled time-stamping support for signing and verification workflows.

**Action Required:**
1. Implement timestamping support in notation-core-go.
2. Enable timestamping support for signing and verification workflows in notation-go.
3. Review verify TSA code which includes CMS parsing and verification. This code was included in alpha.1 and did not get through enough code review.
4. Ensure adequate test coverage in notation-core-go for CMS parsing and verification.

**Comment by gokarnm** [comment]
@shizhMSFT I update the scope in the issue description as discussed earlier.

**Comment by yizha1** [comment]
Based on the community discussion, move this issue out of rc.1 scope
