### ISSUE TITLE
Support signing and verifying tag references

### ISSUE THREAD

**Issue by rgnote** [notaryproject/notation-go#81]
Currently, notation supports signing and verifying digest references only.

**Comment by iamsamirzon** [comment]
@rgnote  - Is this issue in relation to this roadmap item? https://github.com/notaryproject/roadmap/issues/61. If so there is already an issue in Notation for it. https://github.com/notaryproject/notation/issues/194. 

Is this issue in "notation-go" to do some of the implementation.

**Comment by dtzar** [comment]
This is already completed.
