### ISSUE TITLE
notation-go config package

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-go#91]
[notation config](https://github.com/notaryproject/notation/tree/main/pkg/config) is a package for notation-go configuration, so it should be migrated to notation-go repo. Also, according to [directory structure spec](https://github.com/notaryproject/notation/blob/main/specs/directory.md) signingkeys related configuration should be moved out of `config.json` file to be a `signingkeys.json` file.

Related discussion is [here](https://github.com/notaryproject/notation/issues/252#issuecomment-1193751254)

**Comment by JeyJeyGao** [comment]
Junjie Gao is working on this issue.

**Comment by shizhMSFT** [comment]
Closed by #90
