### ISSUE TITLE
Shift Go Support Window to [1.18, 1.19]

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-go#99]
[Go 1.19](https://go.dev/blog/go1.19) is released with [release notes](https://go.dev/doc/go1.19)!

It is time to shift the window for go support to `[1.18, 1.19]` by updating

- `go. mod`
- GitHub Actions via [notation-core-go](https://github.com/notaryproject/notation-core-go)

**Comment by JeyJeyGao** [comment]
I will work on this task.
